export const SCREEN_ID = {
  SIGN_IN_ID: 'SIGN_IN_ID',
  HOME_PAGE_ID: 'HOME_PAGE_ID',
  SETTINGS_ID: 'SETTINGS_ID',
  SIDE_MENU_ID: 'SIDE_MENU_ID',
  FOOD_DETAIL_ID: 'FOOD_DETAIL_ID',
};

export const SCREEN_NAME = {
  SIGN_IN: 'SIGN_IN',
  HOME_PAGE: 'HOME_PAGE',
  SETTINGS: 'SETTINGS',
  SIDE_MENU: 'SIDE_MENU',
  FOOD_DETAIL: 'FOOD_DETAIL',
};
